// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzTtjhgfGrJcF5lxrH4V5oMWS4qmjMFw4',
    appId: '1:937214757402:web:4765ef7236563b2ed81fa3',
    messagingSenderId: '937214757402',
    projectId: 'ecommerce-tt-api',
    authDomain: 'ecommerce-tt-api.firebaseapp.com',
    storageBucket: 'ecommerce-tt-api.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQZlN7fPAFgrs16wQ03C8aBjltyWVPiEA',
    appId: '1:937214757402:android:e73344b247e2baf1d81fa3',
    messagingSenderId: '937214757402',
    projectId: 'ecommerce-tt-api',
    storageBucket: 'ecommerce-tt-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3a5FcTEBVPd4PvMuWhFPntoGx_6mUaPU',
    appId: '1:937214757402:ios:4cd473b0b8370f16d81fa3',
    messagingSenderId: '937214757402',
    projectId: 'ecommerce-tt-api',
    storageBucket: 'ecommerce-tt-api.appspot.com',
    iosBundleId: 'com.example.ecommerceTtApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3a5FcTEBVPd4PvMuWhFPntoGx_6mUaPU',
    appId: '1:937214757402:ios:eb44afadf5be8f6bd81fa3',
    messagingSenderId: '937214757402',
    projectId: 'ecommerce-tt-api',
    storageBucket: 'ecommerce-tt-api.appspot.com',
    iosBundleId: 'com.example.ecommerceTtApi.RunnerTests',
  );
}
